services:
  - type: web
    name: chat-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p 8000 mywebsite.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mywebsite.settings
